# Generated by Django 6.0.5 on 2026-05-19 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dette",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "type_dette",
                    models.CharField(
                        choices=[("emprunt", "J'ai emprunté"), ("pret", "J'ai prêté")],
                        max_length=10,
                    ),
                ),
                ("personne", models.CharField(max_length=200)),
                ("date_echeance", models.DateField()),
                ("rembourse", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
