# Generated by Django 6.0.5 on 2026-05-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alertes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alerte",
            name="type_alerte",
            field=models.CharField(
                choices=[
                    ("budget", "Dépassement budget"),
                    ("objectif", "Objectif atteint"),
                    ("dette", "Échéance dette"),
                    ("solde_negatif", "Solde négatif"),
                    ("doublon", "Transaction en doublon"),
                    ("fraude", "Activité suspecte"),
                ],
                max_length=20,
            ),
        ),
    ]
